name: code_sharp
description: Make the code more sharp.
version: 0.0.1
repository: https://github.com/Nomeleel/code_sharp
issue_tracker: https://github.com/Nomeleel/code_sharp/issues
homepage: https://github.com/Nomeleel/code_sharp

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^3.2.0
  analyzer_plugin: ^0.9.0
  linter: ^1.18.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
